### ISSUE TITLE
Alexa stops listening

### ISSUE THREAD

**Issue by goodpunk6** [xtools-at/AssistantPi#11]
**Python 2 & 3 releases (`python2 --version` and `python3 --version`):**
```
Whatever comes with Jessie Lite
```

**Description of problem:**
```
Alexa will stop listening after saying hello on boot.
```

**Expected:**
```
I expect Alexa to respond when I say Alexa
```

**Steps to reproduce:**

1. Install Assistant Pi with Google and airplay support
2. setup audio to pulse system wide as recommended
3. after a reboot, and after alexa says hello, call alexa

**Traceback (if applicable):**
```

```

**Additional info:**
```
python /opt/AlexaPi/src/main.py -d
INFO: pocketsphinx.c(152): Parsed model-specific feature parameters from /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/feat.params
Current configuration:
[NAME]                  [DEFLT]         [VALUE]
-agc                    none            none
-agcthresh              2.0             2.000000e+00
-allphone
-allphone_ci            no              no
-alpha                  0.97            9.700000e-01
-ascale                 20.0            2.000000e+01
-aw                     1               1
-backtrace              no              no
-beam                   1e-48           1.000000e-48
-bestpath               yes             yes
-bestpathlw             9.5             9.500000e+00
-ceplen                 13              13
-cmn                    live            batch
-cmninit                40,3,-1         41.00,-5.29,-0.12,5.09,2.48,-4.07,-1.37,-1.78,-5.08,-2.05,-6.45,-1.42,1.17
-compallsen             no              no
-debug                                  0
-dict                                   /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/cmudict-en-us.dict
-dictcase               no              no
-dither                 no              no
-doublebw               no              no
-ds                     1               1
-fdict
-feat                   1s_c_d_dd       1s_c_d_dd
-featparams
-fillprob               1e-8            1.000000e-08
-frate                  100             100
-fsg
-fsgusealtpron          yes             yes
-fsgusefiller           yes             yes
-fwdflat                yes             yes
-fwdflatbeam            1e-64           1.000000e-64
-fwdflatefwid           4               4
-fwdflatlw              8.5             8.500000e+00
-fwdflatsfwin           25              25
-fwdflatwbeam           7e-29           7.000000e-29
-fwdtree                yes             yes
-hmm                                    /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us
-input_endian           little          little
-jsgf
-keyphrase
-kws                                    /opt/AlexaPi/src/keyphrase.list
-kws_delay              10              10
-kws_plp                1e-1            1.000000e-01
-kws_threshold          1               1.000000e+00
-latsize                5000            5000
-lda
-ldadim                 0               0
-lifter                 0               22
-lm
-lmctl
-lmname
-logbase                1.0001          1.000100e+00
-logfn
-logspec                no              no
-lowerf                 133.33334       1.300000e+02
-lpbeam                 1e-40           1.000000e-40
-lponlybeam             7e-29           7.000000e-29
-lw                     6.5             6.500000e+00
-maxhmmpf               30000           30000
-maxwpf                 -1              -1
-mdef
-mean
-mfclogdir
-min_endfr              0               0
-mixw
-mixwfloor              0.0000001       1.000000e-07
-mllr
-mmap                   yes             yes
-ncep                   13              13
-nfft                   512             512
-nfilt                  40              25
-nwpen                  1.0             1.000000e+00
-pbeam                  1e-48           1.000000e-48
-pip                    1.0             1.000000e+00
-pl_beam                1e-10           1.000000e-10
-pl_pbeam               1e-10           1.000000e-10
-pl_pip                 1.0             1.000000e+00
-pl_weight              3.0             3.000000e+00
-pl_window              5               5
-rawlogdir
-remove_dc              no              no
-remove_noise           yes             yes
-remove_silence         yes             yes
-round_filters          yes             yes
-samprate               16000           1.600000e+04
-seed                   -1              -1
-sendump
-senlogdir
-senmgau
-silprob                0.005           5.000000e-03
-smoothspec             no              no
-svspec                                 0-12/13-25/26-38
-tmat
-tmatfloor              0.0001          1.000000e-04
-topn                   4               4
-topn_beam              0               0
-toprule
-transform              legacy          dct
-unit_area              yes             yes
-upperf                 6855.4976       6.800000e+03
-uw                     1.0             1.000000e+00
-vad_postspeech         50              50
-vad_prespeech          20              20
-vad_startspeech        10              10
-vad_threshold          2.0             2.000000e+00
-var
-varfloor               0.0001          1.000000e-04
-varnorm                no              no
-verbose                no              no
-warp_params
-warp_type              inverse_linear  inverse_linear
-wbeam                  7e-29           7.000000e-29
-wip                    0.65            6.500000e-01
-wlen                   0.025625        2.562500e-02

INFO: feat.c(715): Initializing feature stream to type: '1s_c_d_dd', ceplen=13, CMN='batch', VARNORM='no', AGC='none'
INFO: acmod.c(166): Using subvector specification 0-12/13-25/26-38
INFO: mdef.c(518): Reading model definition: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/mdef
INFO: mdef.c(531): Found byte-order mark BMDF, assuming this is a binary mdef file
INFO: bin_mdef.c(336): Reading binary model definition: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/mdef
INFO: bin_mdef.c(516): 42 CI-phone, 137053 CD-phone, 3 emitstate/phone, 126 CI-sen, 5126 Sen, 29324 Sen-Seq
INFO: tmat.c(149): Reading HMM transition probability matrices: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/transition_matrices
INFO: acmod.c(117): Attempting to use PTM computation module
INFO: ms_gauden.c(127): Reading mixture gaussian parameter: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/means
INFO: ms_gauden.c(242): 42 codebook, 3 feature, size:
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(127): Reading mixture gaussian parameter: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/variances
INFO: ms_gauden.c(242): 42 codebook, 3 feature, size:
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(304): 222 variance values floored
INFO: ptm_mgau.c(476): Loading senones from dump file /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/sendump
INFO: ptm_mgau.c(500): BEGIN FILE FORMAT DESCRIPTION
INFO: ptm_mgau.c(563): Rows: 128, Columns: 5126
INFO: ptm_mgau.c(595): Using memory-mapped I/O for senones
INFO: ptm_mgau.c(838): Maximum top-N: 4
INFO: phone_loop_search.c(114): State beam -225 Phone exit beam -225 Insertion penalty 0
INFO: dict.c(320): Allocating 138824 * 20 bytes (2711 KiB) for word entries
INFO: dict.c(333): Reading main dictionary: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/cmudict-en-us.dict
INFO: dict.c(213): Dictionary size 134723, allocated 1016 KiB for strings, 1679 KiB for phones
INFO: dict.c(336): 134723 words read
INFO: dict.c(358): Reading filler dictionary: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/noisedict
INFO: dict.c(213): Dictionary size 134728, allocated 0 KiB for strings, 0 KiB for phones
INFO: dict.c(361): 5 words read
INFO: dict2pid.c(396): Building PID tables for dictionary
INFO: dict2pid.c(406): Allocating 42^3 * 2 bytes (144 KiB) for word-initial triphones
INFO: dict2pid.c(132): Allocated 21336 bytes (20 KiB) for word-final triphones
INFO: dict2pid.c(196): Allocated 21336 bytes (20 KiB) for single-phone word triphones
INFO: kws_search.c(406): KWS(beam: -1080, plp: -23, default threshold 0, delay 10)
2017-05-14 14:50:51 DEBUG: Setting up playback handler: VlcHandler
2017-05-14 14:50:54 INFO: Checking Internet Connection ...
2017-05-14 14:50:54 DEBUG: Starting new HTTPS connection (1): api.amazon.com
2017-05-14 14:50:54 DEBUG: https://api.amazon.com:443 "GET /auth/o2/token HTTP/1.1" 404 29
2017-05-14 14:50:54 INFO: Connection OK
2017-05-14 14:50:54 INFO: AVS token: Requesting a new one
2017-05-14 14:50:54 DEBUG: Starting new HTTPS connection (1): api.amazon.com
2017-05-14 14:50:54 DEBUG: https://api.amazon.com:443 "POST /auth/o2/token HTTP/1.1" 200 977
2017-05-14 14:50:54 INFO: AVS token: Obtained successfully
2017-05-14 14:50:54 DEBUG: Stopping audio play
2017-05-14 14:50:55 DEBUG: Playing audio: /opt/AlexaPi/src/resources/hello.mp3
2017-05-14 14:50:55 DEBUG: Player State: State.Opening
2017-05-14 14:50:55 DEBUG: Player State: State.Playing
2017-05-14 14:50:55 DEBUG: Started play.
2017-05-14 14:50:59 DEBUG: Player State: State.Ended
2017-05-14 14:50:59 DEBUG: Finished play.
INFO: kws_search.c(656): kws 2.47 CPU 0.356 xRT
INFO: kws_search.c(658): kws 7.20 wall 1.037 xRT
2017-05-14 14:51:02 DEBUG: Pocketsphinx Trigger found voice command: **google**
2017-05-14 14:51:02 INFO: Starting Assistant conversation
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/AlexaPi/src/main.py", line 595, in trigger_process
    if not assistant_handler(voice_command):
  File "/opt/AlexaPi/src/main.py", line 350, in assistant_handler
    p.expect('Recording audio .*')
  File "/usr/local/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 321, in expect
    timeout, searchwindowsize, async)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 345, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/expect.py", line 105, in expect_loop
    return self.eof(e)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/expect.py", line 50, in eof
    raise EOF(msg)
EOF: End Of File (EOF). Exception style platform.
<pexpect.pty_spawn.spawn object at 0x75df0ab0>
command: /opt/AlexaPi/env/bin/python
args: ['/opt/AlexaPi/env/bin/python', '-m', 'googlesamples.assistant', '--credentials', '/etc/opt/AlexaPi/assistant_credentials.json']
buffer (last 100 chars): ''
before (last 100 chars): 'opt/AlexaPi/src/scripts/auth_assistant.sh  to initialize new OAuth2 credentials.\r\nassistant_record\r\n'
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: 0
flag_eof: True
pid: 957
child_fd: 13
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile("Recording audio .*")



```

**Comment by xtools-at** [comment]
The logs are telling us that the script has crashed - it isn't listening anymore as the app isn't running.

I can even see *why* it crashed:

It starts with
```
2017-05-14 14:51:02 DEBUG: Pocketsphinx Trigger found voice command: **google**
2017-05-14 14:51:02 INFO: Starting Assistant conversation
```
The hotword recognition (mis-?)heard your command and triggered Assistant. Then it fails, and in the Traceback, it says it got stuck on Assistant complaining about
```
... initialize new OAuth2 credentials
```
You haven't done the Authorization with the Google API, this is why the script crashes when Assistant is triggered.

**Comment by xtools-at** [comment]
Hi there,
just a quick hint: I've completed the 1.0 release today, an important fix is included. Please run the Updater script or Assistant might crash otherwise.
