### ISSUE TITLE
it crash after running for awhile 

### ISSUE THREAD

**Issue by ttruong15** [xtools-at/AssistantPi#12]
**Python 2 & 3 releases (`python2 --version` and `python3 --version`):**
```
Python 2.7.9
```

**Description of problem:**
```
Seem to crash after the system run for awhile.  Could be 10mins or an hour but always crash with the following log status:

sudo systemctl status Alexa.service:

May 17 07:51:06 raspberrypi3 python[4843]: INFO: Assistant conversation finished
May 17 07:51:08 raspberrypi3 python[4843]: Exception in thread Thread-1:
May 17 07:51:08 raspberrypi3 python[4843]: Traceback (most recent call last):
May 17 07:51:08 raspberrypi3 python[4843]: File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
May 17 07:51:08 raspberrypi3 python[4843]: self.run()
May 17 07:51:08 raspberrypi3 python[4843]: File "/usr/lib/python2.7/threading.py", line 763, in run
May 17 07:51:08 raspberrypi3 python[4843]: self.__target(*self.__args, **self.__kwargs)
May 17 07:51:08 raspberrypi3 python[4843]: File "/opt/AlexaPi/src/alexapi/triggers/pocketsphinxtrigger.py", line 95, in thread
May 17 07:51:08 raspberrypi3 python[4843]: voice_command = self._decoder.hyp().hypstr
May 17 07:51:08 raspberrypi3 python[4843]: AttributeError: 'NoneType' object has no attribute 'hypstr'


```

**Expected:**
```

```

**Steps to reproduce:**

1.
2. 
3. 

**Traceback (if applicable):**
```

```

**Additional info:**
```

```

**Comment by xtools-at** [comment]
Thanks for reporting, it seems that pocketsphinx here and there returns a null-Object when recognizing hotwords. I'll fix this soon!

EDIT: strange, I've had a null/None check in place already for this...

**Comment by xtools-at** [comment]
just pushed release 1.1, the issue is fixed there.
please run the updater and try again!

**Comment by xtools-at** [comment]
please reopen if the problem still occurs!

**Comment by xtools-at** [comment]
just for the record, I've set up an instance on a Raspi Zero W and it's running fine for 24+ hours in my bathroom :)
