### ISSUE TITLE
Asking Alexa for the Weather throws a file error

### ISSUE THREAD

**Issue by nickexile** [xtools-at/AssistantPi#26]
**Python 2 & 3 releases (`python2 --version` and `python3 --version`):**
Python 2.7.13
Python 3.5.3

**Description of problem:**
When asking Alexa what the weather is, there is an Error.  

IOError: [Errno 2] No such file or directory: '/tmp/AlexaPi-runtime-1sJw90/245ab81e-49c1-4468-959d-6b657f35a017#Alexa3P:1.0/2017/10/27/17/0a925a6ef1964b3691fe5968b3b9cdd6/18:06::TNIH_2V.203601ef-3c63-4033-90bb-c197bde30439ZXV/0_2072418245.mp3'

**Expected:**
Not an error

**Steps to reproduce:**

1. Start AssistantPI
2. Say: "Alexa"
3. Say "what is the weather"

**Traceback (if applicable):**
2017-10-27 13:18:14 DEBUG: Processing Request Response...
2017-10-27 13:18:14 DEBUG: JSON String Returned: {
  "messageBody": {
    "directives": [
      {
        "namespace": "Speaker", 
        "name": "SetMute", 
        "payload": {
          "mute": false
        }
      }, 
      {
        "namespace": "SpeechSynthesizer", 
        "name": "speak", 
        "payload": {
          "contentIdentifier": "amzn1.as-ct.v1.Domain:Application:Weather#ACRI#245ab81e-49c1-4468-959d-6b657f35a017#Alexa3P:1.0/2017/10/27/17/0a925a6ef1964b3691fe5968b3b9cdd6/18:06::TNIH_2V.203601ef-3c63-4033-90bb-c197bde30439ZXV/0", 
          "audioContent": "cid:245ab81e-49c1-4468-959d-6b657f35a017#Alexa3P:1.0/2017/10/27/17/0a925a6ef1964b3691fe5968b3b9cdd6/18:06::TNIH_2V.203601ef-3c63-4033-90bb-c197bde30439ZXV/0_2072418245"
        }
      }
    ]
  }, 
  "messageHeader": {}
}
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/AlexaPi/src/main.py", line 611, in trigger_process
    alexa_speech_recognizer(audio_stream)
  File "/opt/AlexaPi/src/main.py", line 420, in alexa_speech_recognizer
    process_response(resp)
  File "/opt/AlexaPi/src/main.py", line 510, in process_response
    with open(filename, 'wb') as f:
IOError: [Errno 2] No such file or directory: '/tmp/AlexaPi-runtime-1sJw90/245ab81e-49c1-4468-959d-6b657f35a017#Alexa3P:1.0/2017/10/27/17/0a925a6ef1964b3691fe5968b3b9cdd6/18:06::TNIH_2V.203601ef-3c63-4033-90bb-c197bde30439ZXV/0_2072418245.mp3'

**Additional info:**
It looks like there are slashes in the temp data from Alexa, I am thinking this is an issue with the pathing

**Comment by nickexile** [comment]
I modified the main.py according to a fix I found in the AlexaPi project:
https://github.com/alexa-pi/AlexaPi/commit/fec944ed78d028d2cb36f9b1c75451cc5c021e1a

I have attached the modified main.py to this comment. 
[main.py.txt](https://github.com/xtools-at/AssistantPi/files/1422954/main.py.txt)
