### ISSUE TITLE
I can't install the Google Assistant

### ISSUE THREAD

**Issue by EmadMokhtar** [xtools-at/AssistantPi#33]
**Python 2 & 3 releases (`python2 --version` and `python3 --version`):**
```
Python 2.7.16
Python 3.7.3
```

**Description of problem:**
```
I can't install Google Assistant especially when it reaches the point to authenticate.
```

**Expected:**
```
Authenticate to Google Assistant.
```

**Steps to reproduce:**

1. Run `sudo bash /opt/AlexaPi/src/scripts/install_assistant.sh`
2. When it asks for the client's secret, answer no for the default path.
3. Enter a custom path.

**Traceback (if applicable):**
```
Please enter the full path to your client_secret.json (including the filename): /home/pi/client_assistant.json
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/opt/AlexaPi/src/assistant-sdk-python/googlesamples/assistant/auth_helpers/__init__.py", line 20, in <module>
    import google.auth
ModuleNotFoundError: No module named 'google.auth'
```

**Additional info:**
While running `/opt/AlexaPi/env/bin/python -m pip install --upgrade -e ".[samples]"` command, this error will appear.

```
Failed to build grpcio
google-assistant-grpc 0.2.1 has requirement grpcio>=1.3.5, but you'll have grpcio 1.2.1 which is incompatible.
Installing collected packages: googleapis-common-protos, grpcio, google-auth-oauthlib, sounddevice, monotonic, tenacity, urllib3, google-assistant-sdk
  Found existing installation: googleapis-common-protos 1.52.0
    Uninstalling googleapis-common-protos-1.52.0:
      Successfully uninstalled googleapis-common-protos-1.52.0
  Found existing installation: grpcio 1.35.0
    Uninstalling grpcio-1.35.0:
      Successfully uninstalled grpcio-1.35.0
  Running setup.py install for grpcio ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-c0g3jr07/grpcio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ilboxh5w/install-record.txt --single-version-externally-managed --compile:
    Found cython-generated files...
    running install
    running build
    running build_py
    running build_project_metadata
    creating python_build
    creating python_build/lib.linux-armv6l-3.7
    creating python_build/lib.linux-armv6l-3.7/grpc
    copying src/python/grpcio/grpc/_auth.py -> python_build/lib.linux-armv6l-3.7/grpc
    copying src/python/grpcio/grpc/_channel.py -> python_build/lib.linux-armv6l-3.7/grpc
    copying src/python/grpcio/grpc/__init__.py -> python_build/lib.linux-armv6l-3.7/grpc
    copying src/python/grpcio/grpc/_plugin_wrapping.py -> python_build/lib.linux-armv6l-3.7/grpc
    copying src/python/grpcio/grpc/_grpcio_metadata.py -> python_build/lib.linux-armv6l-3.7/grpc
    copying src/python/grpcio/grpc/_credential_composition.py -> python_build/lib.linux-armv6l-3.7/grpc
    copying src/python/grpcio/grpc/_utilities.py -> python_build/lib.linux-armv6l-3.7/grpc
    copying src/python/grpcio/grpc/_common.py -> python_build/lib.linux-armv6l-3.7/grpc
    copying src/python/grpcio/grpc/_server.py -> python_build/lib.linux-armv6l-3.7/grpc
    creating python_build/lib.linux-armv6l-3.7/grpc/beta
    copying src/python/grpcio/grpc/beta/implementations.py -> python_build/lib.linux-armv6l-3.7/grpc/beta
    copying src/python/grpcio/grpc/beta/__init__.py -> python_build/lib.linux-armv6l-3.7/grpc/beta
    copying src/python/grpcio/grpc/beta/_server_adaptations.py -> python_build/lib.linux-armv6l-3.7/grpc/beta
    copying src/python/grpcio/grpc/beta/interfaces.py -> python_build/lib.linux-armv6l-3.7/grpc/beta
    copying src/python/grpcio/grpc/beta/_client_adaptations.py -> python_build/lib.linux-armv6l-3.7/grpc/beta
    copying src/python/grpcio/grpc/beta/utilities.py -> python_build/lib.linux-armv6l-3.7/grpc/beta
    creating python_build/lib.linux-armv6l-3.7/grpc/framework
    copying src/python/grpcio/grpc/framework/__init__.py -> python_build/lib.linux-armv6l-3.7/grpc/framework
    creating python_build/lib.linux-armv6l-3.7/grpc/_cython
    copying src/python/grpcio/grpc/_cython/__init__.py -> python_build/lib.linux-armv6l-3.7/grpc/_cython
    creating python_build/lib.linux-armv6l-3.7/grpc/framework/common
    copying src/python/grpcio/grpc/framework/common/__init__.py -> python_build/lib.linux-armv6l-3.7/grpc/framework/common
    copying src/python/grpcio/grpc/framework/common/style.py -> python_build/lib.linux-armv6l-3.7/grpc/framework/common
    copying src/python/grpcio/grpc/framework/common/cardinality.py -> python_build/lib.linux-armv6l-3.7/grpc/framework/common
    creating python_build/lib.linux-armv6l-3.7/grpc/framework/interfaces
    copying src/python/grpcio/grpc/framework/interfaces/__init__.py -> python_build/lib.linux-armv6l-3.7/grpc/framework/interfaces
    creating python_build/lib.linux-armv6l-3.7/grpc/framework/foundation
    copying src/python/grpcio/grpc/framework/foundation/__init__.py -> python_build/lib.linux-armv6l-3.7/grpc/framework/foundation
    copying src/python/grpcio/grpc/framework/foundation/stream.py -> python_build/lib.linux-armv6l-3.7/grpc/framework/foundation
    copying src/python/grpcio/grpc/framework/foundation/logging_pool.py -> python_build/lib.linux-armv6l-3.7/grpc/framework/foundation
    copying src/python/grpcio/grpc/framework/foundation/callable_util.py -> python_build/lib.linux-armv6l-3.7/grpc/framework/foundation
    copying src/python/grpcio/grpc/framework/foundation/stream_util.py -> python_build/lib.linux-armv6l-3.7/grpc/framework/foundation
    copying src/python/grpcio/grpc/framework/foundation/abandonment.py -> python_build/lib.linux-armv6l-3.7/grpc/framework/foundation
    copying src/python/grpcio/grpc/framework/foundation/future.py -> python_build/lib.linux-armv6l-3.7/grpc/framework/foundation
    creating python_build/lib.linux-armv6l-3.7/grpc/framework/interfaces/face
    copying src/python/grpcio/grpc/framework/interfaces/face/__init__.py -> python_build/lib.linux-armv6l-3.7/grpc/framework/interfaces/face
    copying src/python/grpcio/grpc/framework/interfaces/face/face.py -> python_build/lib.linux-armv6l-3.7/grpc/framework/interfaces/face
    copying src/python/grpcio/grpc/framework/interfaces/face/utilities.py -> python_build/lib.linux-armv6l-3.7/grpc/framework/interfaces/face
    creating python_build/lib.linux-armv6l-3.7/grpc/framework/interfaces/base
    copying src/python/grpcio/grpc/framework/interfaces/base/__init__.py -> python_build/lib.linux-armv6l-3.7/grpc/framework/interfaces/base
    copying src/python/grpcio/grpc/framework/interfaces/base/base.py -> python_build/lib.linux-armv6l-3.7/grpc/framework/interfaces/base
    copying src/python/grpcio/grpc/framework/interfaces/base/utilities.py -> python_build/lib.linux-armv6l-3.7/grpc/framework/interfaces/base
    creating python_build/lib.linux-armv6l-3.7/grpc/_cython/_cygrpc
    copying src/python/grpcio/grpc/_cython/_cygrpc/__init__.py -> python_build/lib.linux-armv6l-3.7/grpc/_cython/_cygrpc
    creating python_build/lib.linux-armv6l-3.7/grpc/_cython/_credentials
    copying src/python/grpcio/grpc/_cython/_credentials/roots.pem -> python_build/lib.linux-armv6l-3.7/grpc/_cython/_credentials
    running build_ext
    Found cython-generated files...
    building 'grpc._cython.cygrpc' extension
    creating python_build/temp.linux-armv6l-3.7
    creating python_build/temp.linux-armv6l-3.7/src
    creating python_build/temp.linux-armv6l-3.7/src/python
    creating python_build/temp.linux-armv6l-3.7/src/python/grpcio
    creating python_build/temp.linux-armv6l-3.7/src/python/grpcio/grpc
    creating python_build/temp.linux-armv6l-3.7/src/python/grpcio/grpc/_cython
    creating python_build/temp.linux-armv6l-3.7/src/core
    creating python_build/temp.linux-armv6l-3.7/src/core/lib
    creating python_build/temp.linux-armv6l-3.7/src/core/lib/profiling
    creating python_build/temp.linux-armv6l-3.7/src/core/lib/support
    creating python_build/temp.linux-armv6l-3.7/src/core/lib/surface
    creating python_build/temp.linux-armv6l-3.7/src/core/lib/channel
    creating python_build/temp.linux-armv6l-3.7/src/core/lib/compression
    creating python_build/temp.linux-armv6l-3.7/src/core/lib/debug
    creating python_build/temp.linux-armv6l-3.7/src/core/lib/http
    creating python_build/temp.linux-armv6l-3.7/src/core/lib/iomgr
    creating python_build/temp.linux-armv6l-3.7/src/core/lib/json
    creating python_build/temp.linux-armv6l-3.7/src/core/lib/slice
    creating python_build/temp.linux-armv6l-3.7/src/core/lib/transport
    creating python_build/temp.linux-armv6l-3.7/src/core/ext
    creating python_build/temp.linux-armv6l-3.7/src/core/ext/transport
    creating python_build/temp.linux-armv6l-3.7/src/core/ext/transport/chttp2
    creating python_build/temp.linux-armv6l-3.7/src/core/ext/transport/chttp2/server
    creating python_build/temp.linux-armv6l-3.7/src/core/ext/transport/chttp2/server/secure
    creating python_build/temp.linux-armv6l-3.7/src/core/ext/transport/chttp2/transport
    creating python_build/temp.linux-armv6l-3.7/src/core/ext/transport/chttp2/alpn
    creating python_build/temp.linux-armv6l-3.7/src/core/lib/security
    creating python_build/temp.linux-armv6l-3.7/src/core/lib/security/context
    creating python_build/temp.linux-armv6l-3.7/src/core/lib/security/credentials
    creating python_build/temp.linux-armv6l-3.7/src/core/lib/security/credentials/composite
    creating python_build/temp.linux-armv6l-3.7/src/core/lib/security/credentials/fake
    creating python_build/temp.linux-armv6l-3.7/src/core/lib/security/credentials/google_default
    creating python_build/temp.linux-armv6l-3.7/src/core/lib/security/credentials/iam
    creating python_build/temp.linux-armv6l-3.7/src/core/lib/security/credentials/jwt
    creating python_build/temp.linux-armv6l-3.7/src/core/lib/security/credentials/oauth2
    creating python_build/temp.linux-armv6l-3.7/src/core/lib/security/credentials/plugin
    creating python_build/temp.linux-armv6l-3.7/src/core/lib/security/credentials/ssl
    creating python_build/temp.linux-armv6l-3.7/src/core/lib/security/transport
    creating python_build/temp.linux-armv6l-3.7/src/core/lib/security/util
    creating python_build/temp.linux-armv6l-3.7/src/core/lib/tsi
    creating python_build/temp.linux-armv6l-3.7/src/core/ext/transport/chttp2/client
    creating python_build/temp.linux-armv6l-3.7/src/core/ext/transport/chttp2/client/secure
    creating python_build/temp.linux-armv6l-3.7/src/core/ext/client_channel
    creating python_build/temp.linux-armv6l-3.7/src/core/ext/transport/chttp2/server/insecure
    creating python_build/temp.linux-armv6l-3.7/src/core/ext/transport/chttp2/client/insecure
    creating python_build/temp.linux-armv6l-3.7/src/core/ext/lb_policy
    creating python_build/temp.linux-armv6l-3.7/src/core/ext/lb_policy/grpclb
    creating python_build/temp.linux-armv6l-3.7/src/core/ext/lb_policy/grpclb/proto
    creating python_build/temp.linux-armv6l-3.7/src/core/ext/lb_policy/grpclb/proto/grpc
    creating python_build/temp.linux-armv6l-3.7/src/core/ext/lb_policy/grpclb/proto/grpc/lb
    creating python_build/temp.linux-armv6l-3.7/src/core/ext/lb_policy/grpclb/proto/grpc/lb/v1
    creating python_build/temp.linux-armv6l-3.7/third_party
    creating python_build/temp.linux-armv6l-3.7/third_party/nanopb
    creating python_build/temp.linux-armv6l-3.7/src/core/ext/lb_policy/pick_first
    creating python_build/temp.linux-armv6l-3.7/src/core/ext/lb_policy/round_robin
    creating python_build/temp.linux-armv6l-3.7/src/core/ext/resolver
    creating python_build/temp.linux-armv6l-3.7/src/core/ext/resolver/dns
    creating python_build/temp.linux-armv6l-3.7/src/core/ext/resolver/dns/native
    creating python_build/temp.linux-armv6l-3.7/src/core/ext/resolver/sockaddr
    creating python_build/temp.linux-armv6l-3.7/src/core/ext/load_reporting
    creating python_build/temp.linux-armv6l-3.7/src/core/ext/census
    creating python_build/temp.linux-armv6l-3.7/src/core/ext/census/gen
    creating python_build/temp.linux-armv6l-3.7/src/core/plugin_registry
    creating python_build/temp.linux-armv6l-3.7/src/boringssl
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/aes
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/asn1
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/base64
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/bio
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/bn
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/bn/asm
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/buf
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/bytestring
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/chacha
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/cipher
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/cmac
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/conf
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/curve25519
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/des
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/dh
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/digest
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/dsa
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/ec
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/ecdh
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/ecdsa
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/engine
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/err
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/evp
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/hkdf
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/hmac
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/lhash
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/md4
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/md5
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/modes
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/newhope
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/obj
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/pem
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/pkcs8
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/poly1305
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/rand
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/rc4
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/rsa
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/sha
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/stack
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/x509
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/crypto/x509v3
    creating python_build/temp.linux-armv6l-3.7/third_party/boringssl/ssl
    creating python_build/temp.linux-armv6l-3.7/third_party/zlib
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DOPENSSL_NO_ASM=1 -D_WIN32_WINNT=1536 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DPyMODINIT_FUNC=__attribute__((visibility ("default"))) PyObject* -Isrc/python/grpcio -Iinclude -I. -Ithird_party/boringssl/include -Ithird_party/zlib -I/usr/include/python3.7m -c src/python/grpcio/grpc/_cython/cygrpc.c -o python_build/temp.linux-armv6l-3.7/src/python/grpcio/grpc/_cython/cygrpc.o -fvisibility=hidden -fno-wrapv -pthread -std=gnu99
    src/python/grpcio/grpc/_cython/cygrpc.c: In function '__Pyx_PyCFunction_FastCall':
    src/python/grpcio/grpc/_cython/cygrpc.c:29815:13: error: too many arguments to function '(PyObject * (*)(PyObject *, PyObject * const*, Py_ssize_t))meth'
         return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
                ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/python/grpcio/grpc/_cython/cygrpc.c: In function '__Pyx__ExceptionSave':
    src/python/grpcio/grpc/_cython/cygrpc.c:31119:21: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
         *type = tstate->exc_type;
                         ^~~~~~~~
                         curexc_type
    src/python/grpcio/grpc/_cython/cygrpc.c:31120:22: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
         *value = tstate->exc_value;
                          ^~~~~~~~~
                          curexc_value
    src/python/grpcio/grpc/_cython/cygrpc.c:31121:19: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
         *tb = tstate->exc_traceback;
                       ^~~~~~~~~~~~~
                       curexc_traceback
    src/python/grpcio/grpc/_cython/cygrpc.c: In function '__Pyx__ExceptionReset':
    src/python/grpcio/grpc/_cython/cygrpc.c:31128:24: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
         tmp_type = tstate->exc_type;
                            ^~~~~~~~
                            curexc_type
    src/python/grpcio/grpc/_cython/cygrpc.c:31129:25: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
         tmp_value = tstate->exc_value;
                             ^~~~~~~~~
                             curexc_value
    src/python/grpcio/grpc/_cython/cygrpc.c:31130:22: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
         tmp_tb = tstate->exc_traceback;
                          ^~~~~~~~~~~~~
                          curexc_traceback
    src/python/grpcio/grpc/_cython/cygrpc.c:31131:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
         tstate->exc_type = type;
                 ^~~~~~~~
                 curexc_type
    src/python/grpcio/grpc/_cython/cygrpc.c:31132:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
         tstate->exc_value = value;
                 ^~~~~~~~~
                 curexc_value
    src/python/grpcio/grpc/_cython/cygrpc.c:31133:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
         tstate->exc_traceback = tb;
                 ^~~~~~~~~~~~~
                 curexc_traceback
    src/python/grpcio/grpc/_cython/cygrpc.c: In function '__Pyx__GetException':
    src/python/grpcio/grpc/_cython/cygrpc.c:31188:24: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
         tmp_type = tstate->exc_type;
                            ^~~~~~~~
                            curexc_type
    src/python/grpcio/grpc/_cython/cygrpc.c:31189:25: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
         tmp_value = tstate->exc_value;
                             ^~~~~~~~~
                             curexc_value
    src/python/grpcio/grpc/_cython/cygrpc.c:31190:22: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
         tmp_tb = tstate->exc_traceback;
                          ^~~~~~~~~~~~~
                          curexc_traceback
    src/python/grpcio/grpc/_cython/cygrpc.c:31191:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
         tstate->exc_type = local_type;
                 ^~~~~~~~
                 curexc_type
    src/python/grpcio/grpc/_cython/cygrpc.c:31192:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
         tstate->exc_value = local_value;
                 ^~~~~~~~~
                 curexc_value
    src/python/grpcio/grpc/_cython/cygrpc.c:31193:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
         tstate->exc_traceback = local_tb;
                 ^~~~~~~~~~~~~
                 curexc_traceback
    creating tmp/tmp3gd_kksx
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -c /tmp/tmp3gd_kksx/a.c -o tmp/tmp3gd_kksx/a.o
    Traceback (most recent call last):
      File "/usr/lib/python3.7/distutils/unixccompiler.py", line 118, in _compile
        extra_postargs)
      File "/tmp/pip-install-c0g3jr07/grpcio/src/python/grpcio/_spawn_patch.py", line 69, in _commandfile_spawn
        _classic_spawn(self, command)
      File "/usr/lib/python3.7/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/lib/python3.7/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-c0g3jr07/grpcio/src/python/grpcio/commands.py", line 281, in build_extensions
        build_ext.build_ext.build_extensions(self)
      File "/usr/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 199, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
        depends=ext.depends)
      File "/usr/lib/python3.7/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/lib/python3.7/distutils/unixccompiler.py", line 120, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-c0g3jr07/grpcio/setup.py", line 280, in <module>
        cmdclass=COMMAND_CLASS,
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.7/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 78, in run
        _build_ext.run(self)
      File "/usr/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/tmp/pip-install-c0g3jr07/grpcio/src/python/grpcio/commands.py", line 286, in build_extensions
        "Failed `build_ext` step:\n{}".format(formatted_exception))
    commands.CommandError: Failed `build_ext` step:
    Traceback (most recent call last):
      File "/usr/lib/python3.7/distutils/unixccompiler.py", line 118, in _compile
        extra_postargs)
      File "/tmp/pip-install-c0g3jr07/grpcio/src/python/grpcio/_spawn_patch.py", line 69, in _commandfile_spawn
        _classic_spawn(self, command)
      File "/usr/lib/python3.7/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/lib/python3.7/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-c0g3jr07/grpcio/src/python/grpcio/commands.py", line 281, in build_extensions
        build_ext.build_ext.build_extensions(self)
      File "/usr/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 199, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
        depends=ext.depends)
      File "/usr/lib/python3.7/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/lib/python3.7/distutils/unixccompiler.py", line 120, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    
    
    ----------------------------------------
  Rolling back uninstall of grpcio
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-c0g3jr07/grpcio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ilboxh5w/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-c0g3jr07/grpcio/
```

**Comment by EmadMokhtar** [comment]
The problem is with the Python 3 version. I'm using 3.7 and I think the old Assistant repo is using older version. This is the reason of the compilation issues.
